**Implement 10x10 associative memory (binary) using Hopfield network.**


In [1]:
import numpy as np

# Initialize the size of the Hopfield network (10x10 binary associative memory)
n_neurons = 100

In [2]:
# Generate some random binary patterns (-1 and 1) to store in the network
np.random.seed(0)
num_patterns = 10
patterns = np.random.choice([-1, 1], size=(num_patterns, n_neurons))

In [3]:
# Step 1: Compute the weight matrix using Hebbian learning
W = np.zeros((n_neurons, n_neurons))
for p in patterns:
    W += np.outer(p, p)
np.fill_diagonal(W, 0)



In [4]:
# Step 2: Define the update rule for the Hopfield network
def hopfield_update(state, weights):
    """Update the state of the Hopfield network."""
    new_state = np.sign(weights @ state)
    new_state[new_state == 0] = 1  # Handle zero as +1
    return new_state



In [5]:
# Step 3: Test the network with a noisy version of a stored pattern
def test_hopfield(pattern, weights, iterations=5):
    """Test the network's ability to recover a pattern."""
    noisy_pattern = pattern.copy()
    noise_indices = np.random.choice(len(pattern), size=len(pattern) // 4, replace=False)
    noisy_pattern[noise_indices] *= -1
    state = noisy_pattern
    print("Initial noisy pattern:")
    print(state.reshape(10, 10))

    for _ in range(iterations):
        state = hopfield_update(state, weights)

    print("\nRecovered pattern:")
    print(state.reshape(10, 10))
    return state

In [6]:
# Select a pattern to test
test_pattern = patterns[0]

# Test the network's performance
recovered_pattern = test_hopfield(test_pattern, W)

Initial noisy pattern:
[[-1  1  1  1 -1  1  1  1  1  1]
 [ 1  1 -1  1  1 -1 -1  1 -1  1]
 [-1  1 -1 -1 -1  1  1 -1  1 -1]
 [ 1 -1  1 -1  1 -1 -1 -1  1 -1]
 [ 1  1  1  1  1  1 -1  1 -1  1]
 [-1  1  1  1  1  1  1 -1  1  1]
 [-1 -1  1  1  1 -1 -1 -1 -1 -1]
 [ 1  1 -1 -1  1  1  1 -1 -1 -1]
 [-1 -1 -1  1 -1  1  1  1  1 -1]
 [ 1  1  1  1 -1 -1 -1 -1  1  1]]

Recovered pattern:
[[-1.  1.  1. -1.  1.  1.  1.  1.  1.  1.]
 [ 1. -1. -1.  1. -1. -1. -1. -1. -1.  1.]
 [-1.  1.  1. -1. -1.  1.  1.  1.  1. -1.]
 [ 1. -1.  1. -1.  1.  1. -1.  1.  1. -1.]
 [-1.  1. -1.  1.  1.  1.  1.  1. -1.  1.]
 [-1.  1.  1.  1.  1. -1.  1. -1. -1.  1.]
 [ 1. -1.  1. -1.  1. -1. -1. -1. -1. -1.]
 [ 1.  1. -1. -1. -1.  1.  1. -1.  1. -1.]
 [-1.  1. -1.  1.  1.  1.  1.  1.  1. -1.]
 [ 1.  1. -1. -1.  1. -1. -1.  1.  1. -1.]]
