4.2 jigsaw puzzles problem

In [ ]:
import numpy as np
import random
import math

def load_scrambled_image(file_path):
    return np.random.rand(4, 4)

def calculate_cost(puzzle, goal):
    cost = 0
    n = puzzle.shape[0]
    for i in range(n):
        for j in range(n):
            if puzzle[i, j] != goal[i, j]:
                cost += 1
    return cost

def swap_pieces(puzzle):
    n = puzzle.shape[0]
    i1, j1 = random.randint(0, n-1), random.randint(0, n-1)
    i2, j2 = random.randint(0, n-1), random.randint(0, n-1)
    new_puzzle = puzzle.copy()
    new_puzzle[i1, j1], new_puzzle[i2, j2] = new_puzzle[i2, j2], new_puzzle[i1, j1]
    return new_puzzle

def simulated_annealing(puzzle, goal, initial_temp, final_temp, alpha):
    current_state = puzzle
    current_cost = calculate_cost(current_state, goal)
    temp = initial_temp

    while temp > final_temp:
        next_state = swap_pieces(current_state)
        next_cost = calculate_cost(next_state, goal)

        if next_cost < current_cost or random.uniform(0, 1) < math.exp((current_cost - next_cost) / temp):
            current_state = next_state
            current_cost = next_cost

        temp *= alpha

    return current_state

scrambled_image = load_scrambled_image('scrambled_lena.mat')
goal_image = np.sort(scrambled_image, axis=None).reshape(scrambled_image.shape)

initial_temp = 1000
final_temp = 1
alpha = 0.99

solved_puzzle = simulated_annealing(scrambled_image, goal_image, initial_temp, final_temp, alpha)

print(solved_puzzle)

[[0.00914287 0.44976661 0.5666929  0.57094046]
 [0.17364149 0.40767951 0.99359103 0.86469318]
 [0.6629643  0.23807259 0.08290703 0.86161175]
 [0.8597748  0.71489008 0.23959045 0.794777  ]]
